permalink: /:categories/:year/:month/:day/:title/

exclude: [".rvmrc", "README.md", "Rakefile"]

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

title : marcgg#blog
author :
  name : Marc G Gauthier
  email : marcg.gauthier@gmail.com

production_url : https://marcgg.com

collections:
  - books

gems:
  - jekyll-redirect-from
